import type { Metadata } from "next";
import { Manrope, Wix_Madefor_Display } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "@/components/providers/SmoothScroll";

const manropeSans = Manrope({
   variable: "--font-nunito-sans",
   subsets: ["latin", "cyrillic"],
});

const unboundedMono = Wix_Madefor_Display({
   variable: "--font-unbounded-mono",
   subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
   title: "Арман Бабаян - Разработчик Next.js",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${manropeSans.variable} ${unboundedMono.variable} h-full antialiased`}
      >
         <body className="min-h-full flex flex-col">
            <SmoothScroll>
               {children}
            </SmoothScroll>
         </body>
      </html>
   );
}
