import type { Metadata } from "next";
import { Manrope, Unbounded } from "next/font/google";
import "./globals.css";

const manropeSans = Manrope({
   variable: "--font-nunito-sans",
   subsets: ["latin"],
});

const unboundedMono = Unbounded({
   variable: "--font-unbounded-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Арман Бабаян - Разработчик Next.js",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${manropeSans.variable} ${unboundedMono.variable} h-full antialiased`}
      >
         <body className="min-h-full flex flex-col">{children}</body>
      </html>
   );
}
