import type { Metadata } from "next";
import { Manrope, Wix_Madefor_Display, Geist } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "@/components/providers/SmoothScroll";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const manropeSans = Manrope({
    variable: "--font-nunito-sans",
    subsets: ["latin", "cyrillic"],
});

const unboundedMono = Wix_Madefor_Display({
    variable: "--font-unbounded-mono",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Арман Бабаян - Разработчик Next.js",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", manropeSans.variable, unboundedMono.variable, "font-sans", geist.variable)}
        >
            <body className="min-h-full flex flex-col">
                <SmoothScroll>
                    {children}
                </SmoothScroll>
                <Toaster />
            </body>
        </html>
    );
}
